import { ArrowRight, Clock3, Radio, ShieldCheck, Trophy, Volume2 } from "lucide-react";
import { Link } from "react-router-dom";
import { useLanguage } from "../context/LanguageContext";
import { siteConfig } from "../data/siteConfig";
import logo from "../assets/QuizarLogo.jpeg";
import "./Home.css";
export default function Home(){const{t}=useLanguage();
const icons=[Clock3,ShieldCheck,Trophy];
return <div className="home-page"><section className="home-hero"><div className="page-container home-hero-container"><div className="home-hero-content"><div className="home-badge"><Radio size={16}/>{t.home.badge}</div><h1 className="home-title"><span>{t.home.titleStart}</span><span className="gradient-text">{t.home.titleHighlight}</span></h1><p className="home-description">{t.home.description}</p><div className="home-actions"><Link to="/rules" className="home-button primary">{t.home.rulesButton}<ArrowRight size={18}/></Link><Link to="/leaderboard" className="home-button secondary">{t.home.leaderboardButton}</Link></div></div><div className="home-logo-stage"><div className="home-logo-ring"/><div className="home-logo-card"><img src={logo} alt="Quizar Community Trivia"/></div></div></div></section><section className="home-stats"><div className="page-container home-stats-grid">{t.home.stats.map((s,i)=>{const I=icons[i];return <article className="glass-card home-stat" key={s.label}><I/><strong>{s.value}</strong><span>{s.label}</span></article>})}</div></section><section className="page-section"><div className="page-container"><article className="glass-card home-feature"><div><span className="home-eyebrow">{t.home.rulesPreview.eyebrow}</span><h2>{t.home.rulesPreview.title}</h2><p>{t.home.rulesPreview.description}</p></div><Link to="/rules" className="home-text-link">{t.home.rulesPreview.button}<ArrowRight size={18}/></Link></article></div></section><section className="page-section"><div className="page-container home-live"><div className="home-live-screen"><span className="live-status">{t.home.live.status}</span><Radio size={64}/></div><div className="home-live-content"><span className="home-eyebrow">{t.home.live.eyebrow}</span><h2>{t.home.live.title}</h2><p>{t.home.live.description}</p><a className={`home-button secondary ${!siteConfig.youtube.channelUrl?"disabled":""}`} href={siteConfig.youtube.channelUrl||undefined}>{t.home.live.button}</a></div></div></section><section className="page-section"><div className="page-container"><article className="glass-card sound-highlight"><Volume2/><div><span className="home-eyebrow">{t.home.sound.eyebrow}</span><h2>{t.home.sound.title}</h2><p>{t.home.sound.description}</p></div></article></div></section></div>}
